const mockData = {
    fornecedores: [
        { id: 1, nome: "1000MEDIC DISTRIBUIDORA IMP EXP DE MEC", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 2, nome: "ACCUMED PRODUTOS MED. HOSPITALARES LT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 3, nome: "ADELINO AUTO ELETRICA LTDA ME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 4, nome: "ADILSO MASCHIO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 5, nome: "AEROTRIO ALIMENTOS LIMITADA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 6, nome: "AGAPLASTIC INDUSTRIA E COMERCIO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 7, nome: "ALESSANDRO LOPES PEREIRA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 8, nome: "ALIADOS COMUNICACAO VISUAL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 9, nome: "ALIEVI DISTR DE PROD DESCARTAVEIS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 10, nome: "ALMEIDA E RIZZIERI LTDA - ΜΕ", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 11, nome: "ALTERMED MATERIAL MEDICO HOSPITALAR L", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 12, nome: "ALTHAIA S/A IND FARMACEUTICA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 13, nome: "ALTHIS COM DE MEDICAMENTOS E MAT MÉD:", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 14, nome: "AMERICANAS S.A - EM RECUPERACAO JUDICL", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 15, nome: "AMERICANAS S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 16, nome: "AMORIM E SANTOS SALGADOS GOURMET LTC", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 17, nome: "AMPERNET-TELECOMUNICACOES LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 18, nome: "ANA PAULA COMERCIO EQUIPAMENTOS MEDI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 19, nome: "ANDRESSA NEPOMUCENO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 20, nome: "ANICIO PEDRO SCARABELOT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 21, nome: "ATACADO PERTUTTI LTDA ΜΕ", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 22, nome: "ATAMI FORROS E DIVISORIAS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 23, nome: "ATHOS COMERCIAL HOSPITALAR LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 24, nome: "ATITUDE AMBIENTAL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 25, nome: "ATIVA COMERCIAL HOSPITALAR LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 26, nome: "AUTO POSTO BS PREMIUM LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 27, nome: "AUTO POSTO ITAPETININGA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 28, nome: "AVAGUI DISTRIBIDORA DE PRODUTOS AGROI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 29, nome: "B TRANSPORTES LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 30, nome: "B. TRANSPORTES LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 31, nome: "B.TRANSPORTES LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 32, nome: "BAGGIO MOEMA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 33, nome: "BAUER POSTOS COM. DE COMB. E CONVENIEI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 34, nome: "BELFAR LTDA - MATOZINHOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 35, nome: "BEST FABRIL INDUSTRIA E COMERCIO DE AR", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 36, nome: "BFTECH EQUIPAMENTOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 37, nome: "ΒΙΟΝEXO S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 38, nome: "BLUMED DIST DE MEDICAMENTOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 39, nome: "BOLSA BRASILEIRA DE MERCADORIAS-BBM", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 40, nome: "BRASPRESS TRANSPORTES URGENTES LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 41, nome: "CABANA BURGER S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 42, nome: "CENTER PB COMERCIO DE PAPEIS EIRELI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 43, nome: "CENTERMEDI-COMERCIO DE PRODUTOS HOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 44, nome: "CENTRAL DE SERVICOS TEC REIS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 45, nome: "CENTRALVET COMERCIAL DISTRIBUIDORA LT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 46, nome: "CHOCOLATES PATO BRANCO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 47, nome: "CIFARMA CIENTIFICA FARMACEUTICA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 48, nome: "CISA CONSORCIO INTERMUNICIPAL DO NOF", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 49, nome: "CLEITYSON LUCENA COSTA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 50, nome: "COMERCIAL ALIEVI LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 51, nome: "COMERCIAL CIRURGICA RIOCLARENSE LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 52, nome: "COMERCIO DE VACINAS E SERVICOS IMUNIZE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 53, nome: "COPEL DISTRIBUICAO S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 54, nome: "CORREARIA BOLICHO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 55, nome: "CURITIBA INDÚSTRIA COMÉRCIO E REP. DE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 56, nome: "DALCI DAMBROS - PROLABORE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 57, nome: "DALLA VALLE REAL COMERCIO DE UTENSILIO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 58, nome: "DE MORAIS E MORELATTO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 59, nome: "DELL COMPUTADORES DO BRASIL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 60, nome: "DI CASA REFEICOES LIMITADA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 61, nome: "DIFE DISTRIBUIDORA DE MEDICAMENTOS LT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 62, nome: "DIFIO PRODUTOS MEDICOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 63, nome: "DIMED S/A - DISTRIBUIDORA DE MEDICAMEN", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 64, nome: "DISTRIBUIDORA DE MEDICAMENTOS CASARO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 65, nome: "DISTRIBUIDORA MERISIO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 66, nome: "DMB DISTRIBUIDORA DE MEDICAMENTOS BE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 67, nome: "DOC MED COMERCIO IMPORTACAO E EXPORT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 68, nome: "DONIZETTI DE SOUSA GUERREIRO-DESCART/", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 69, nome: "DORJA INDE COMDE EQUIPMEDLTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 70, nome: "DOUGLAS CALEFFI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 71, nome: "DRIMATRI LOJA DE CONVENIENCIAS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 72, nome: "DUOTEC EMBALAGENS LTDA EPP", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 73, nome: "EB PRODUTOS FARMACEUTICOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 74, nome: "EBRAM PRODUTOS LABORATORIAIS LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 75, nome: "ECUSTOMIZE CONSULTORIA EM SOFTWARES", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 76, nome: "EDSON RODRIGO BORDIGNON ME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 77, nome: "ELIANE MARIA BRAZZO - ALUGUEL SALA SECL", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 78, nome: "ELISA CAROLINA DE CARVALHO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 79, nome: "ELOHIM PRODUTOS MEDICOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 80, nome: "EMBRAST INDUSTRIA E COMERCIO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 81, nome: "EMERSON SANTAΝΑ", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 82, nome: "ENDURANCE HOSTGATOR BRASIL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 83, nome: "ERIMAR INDUSTRIA E COMERCIO DE PRODUT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 84, nome: "EUCATUR-EMP. UNIAO CASCAVEL DE TRANS", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 85, nome: "EXCELLENCE TRANSPORTES E LOGISTICA-EI", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 86, nome: "EXPRESSO PRINCESA DOS CAMPOS", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 87, nome: "FA COMERCIO DE PRODUTOS ORTOPEDICOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 88, nome: "FABRICA DE ARTEF.DE LATEX SAO ROQUE LT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 89, nome: "FARMACE - INDUSTRIA QUIMICO FARMACEUT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 90, nome: "FARMAMED IMPORTADORA E DISTR DE MEDI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 91, nome: "FERNAMED LTDA EPP", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 92, nome: "FIA COMERCIO DE PRODUTOS HOSPITALARES", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 93, nome: "FINE LINEA PAES E DOCES LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 94, nome: "FIRSTLAB INDUSTRIA IMPORT. E EXP. DE PRC", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 95, nome: "FORT LOG EIRELI ME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 96, nome: "FURACAO PET INDUSTRIA E COMERCIO DE AF", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 97, nome: "GB INDUSTRIA E COMERCIO DE PLASTICOS E", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 98, nome: "GHI HOTELARIA E TURISMO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 99, nome: "GIGANTEC COMERCIO ELETRONICO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 100, nome: "GIOVANI LEIRIA FERREIRA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 101, nome: "GOLDEN DISTRIBUIDORA LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 102, nome: "GOLDSTAR COMERCIO ATACADISTA E SERVIÇ", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 103, nome: "GRAZIANO & BRAVA COMERCIO E SERVICOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 104, nome: "GREEN FARMACEUTICA EIRELI EPP", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 105, nome: "HB 1 RESTAURANTE LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 106, nome: "HABITABR DISTRIBUIDORA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 107, nome: "HB COMERCIAL DE ALIMENTOS LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 108, nome: "HOSPIDROGAS COMERCIO DE PRODUTOS HO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 109, nome: "HUB INSTITUIÇÃO DE PAGAMENTO S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 110, nome: "I. S. COSTA CENTRAL TELEMEDICINA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 111, nome: "IMEC INDUSTRIA DE MEDICAMENTOS CUSTI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 112, nome: "IN-DENTAL PRODUTOS ODONTOLOGICOS, ME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 113, nome: "INDUSTRIA E COMERCIO DE PRODUTOS PARA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 114, nome: "INSTITUTO NACIONAL DA PROPRIEDADE IND", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 115, nome: "INTERTECH IND DE PROD MEDICOS HOSPITA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 116, nome: "INTRACARGO TRANSP RODOV DE CARGAS EIF", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 117, nome: "ISOART INDUSTRIA DE PRODUTOS TERMICOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 118, nome: "JN INFORMATICA - EIRELI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 119, nome: "JOAO MARCELO DOS REIS DE SOUZA 0842646", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 120, nome: "JOINVILLE - EXPRESSO SAO MIGUEL S/A", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 121, nome: "JOSEANE DA ROSA COLACO LUNELLI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 122, nome: "KELLDRIN INDUSTRIAL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 123, nome: "KRALEN SISTEMAS EIRELI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 124, nome: "LABORATORIO CATARINENSE FILIAL GOIAS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 125, nome: "LASER TECH CARTUCHOS LTDA - ME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 126, nome: "LEMON BRASIL COM DE PROD ELETRONICOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 127, nome: "LEONIR DE MORAES - FRETE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 128, nome: "LF COMERCIAL DE BENS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 129, nome: "LICITANET LICITACOES ELETRONICAS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 130, nome: "LICITAR DIGITAL SERVICOS EM TECNOLOGIA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 131, nome: "LICITASYS CONSULTORIA & ASSESSORIA EMF", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 132, nome: "LPT SERVICOS EM TECNOLOGIA DA INFORMA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 133, nome: "LUFT E FRANCA TRANSPORTES LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 134, nome: "LUMANN DISTRIBUIDORA DE MEDICAMENTOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 135, nome: "LUPLAST IND E COM DE LUVAS DESCARTAVEI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 136, nome: "M&R EMPRESA ALIMENTICIA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 137, nome: "MAGAZINE AVENIDA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 138, nome: "MAGAZINE LUIZA S/A", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 139, nome: "MANFROI & SOUZA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 140, nome: "ΜΑΝΙΑ COMERCIO DE ELETRONICOS LTDA-", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 141, nome: "MARDEK COMERCIO E BENEFICIAMENTO DE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 142, nome: "MARINGA HOSPITALAR DISTR DE MEDICAMEN", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 143, nome: "MAURONEY APARECIDO - CARTORIO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 144, nome: "MED ALPHA DISTRIBUIDORA DE PRODUTOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 145, nome: "MEDCHAP DIST. DE MED. CHAPECO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 146, nome: "MEDCLEAN PRODUTOS HOSPITALARES LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 147, nome: "MEDICAMENTAL DISTRIBUIDORA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 148, nome: "MEDSALUS INDUSTRIA E COMERCIO DE PROC", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 149, nome: "MEGA ESTACIONAMENTO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 150, nome: "MENGUE EXPRESS EIRELLI", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 151, nome: "MERCUR S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 152, nome: "METALURGICA SUPRA STEEL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 153, nome: "MIDFARMA PRODUTOS FARMACEUTICOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 154, nome: "MIGMED MED. E MAT. HOSP. EIRELI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 155, nome: "MULTILASER INDUSTRIAL S.A..", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 156, nome: "MULTISCY TRANSPORTES EIRELI", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 157, nome: "MUNICIPIO DE PATO BRANCO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 158, nome: "MZZ COMERCIO DE PRODUTOS PARA SAUDE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 159, nome: "NACIONAL COMERCIAL HOSPITALAR S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 160, nome: "NATIVITA INDUSTRIA E COMERCIO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 161, nome: "NELSON GLOWACKI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 162, nome: "NEOSUL S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 163, nome: "NEREU RUBES TATARA - POUSADA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 164, nome: "NETLAB EQUIPAMENTOS PARA LABORATORIC", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 165, nome: "NEXT TRADING COMERCIAL", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 166, nome: "NEXT TRADING COMERCIAL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 167, nome: "NIEVE FRAL PRODUTOS DE HIGIENE PESSOAL", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 168, nome: "OESTE PHARMA DISTRIBUIDORA DE MEDICAM", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 169, nome: "ORIENTAR CONTADORES ASSOCIADOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 170, nome: "OTAVIO FELIPE DOS SANTOS 09491616919", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 171, nome: "OURO FARMA COMERCIO DE MEDICAMENTOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 172, nome: "PA SANTOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 173, nome: "PANTHER IND COM EXP DE FRL PRD HIG EIRE", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 174, nome: "PAPEL SHOPP PAPELARIA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 175, nome: "PATO BRANCO 2 TABELIONATO DE NOTAS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 176, nome: "PATO COMERCIO DE COMBUSTIVEIS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 177, nome: "PATOMEDI DISTRIBUIDORA DE MEDICAMENT", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 178, nome: "PB ADMINISTRADORA DE ESTACIONAMENTOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 179, nome: "PJD-COMERCIO DE PRODUTOS VETERINARI(", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 180, nome: "PNEU FREE DO BRASIL COMERCIO ELETRONIC", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 181, nome: "POLAZZO E POLAZZO LTDA - ME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 182, nome: "POLIMEDICI ASSESSORIA E CONSULTORIA EM", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 183, nome: "PONTUAL FARMACÊUTICA NR2006 LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 184, nome: "POTENCIAL METAL INDUSTRIA E COMERCIO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 185, nome: "PROGRESSO MED DISTRIBUIDORA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 186, nome: "PROINLAB - INDUSTRIA E COMERCIO DE PRO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 187, nome: "PROMEFARMA MEDICAMENTOS E PRODUTOS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 188, nome: "REDE NACIONAL DE ENCOMENDAS LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 189, nome: "RIOQUIMICA S.A.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 190, nome: "RODOLFO FARAH VALENTE ΜΕ", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 191, nome: "RODONAVES TRANSP E ENCOMENDAS LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 192, nome: "RODONAVES TRANSPORTES E ENCOMENDAS", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 193, nome: "ROMY COMERCIO DE ALIMENTOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 194, nome: "RZ EQUIPAMENTOS VETERINARIOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 195, nome: "SALAZAR E GUERRA FARMACIA DE MANIPULA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 196, nome: "SALUTE MANGUEIRINHA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 197, nome: "SALUTE MARCEL", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 198, nome: "SALUTEM COMERCIO DE MOVEIS HOSPITALAI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 199, nome: "SAMIR MACHADO DO AMARAL", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 200, nome: "SBF COMERCIO DE PRODUTOS ESPORTIVOS S", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 201, nome: "SCHUSTER COMERCIO DE EQUIPAMENTOS OD", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 202, nome: "SERGIO LUIZ BOESING", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 203, nome: "SERVIMED COMERCIAL LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 204, nome: "SG TECNOLOGIA CLINICA LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 205, nome: "SHALON FIOS CIRURGICOS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 206, nome: "SHIMI COMERCIO DE COMBUSTIVEIS LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 207, nome: "SINDICATO DOS FARMACEUTICOS NO ESTADI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 208, nome: "SLONSKI & CIA LTDA - SUPER POLO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 209, nome: "SMART BUSINESS SERVICE LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 210, nome: "STANG & STANG LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 211, nome: "STRA NEGOCIOS EM SAUDE E BEM ESTAR LTI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 212, nome: "SUPER-PRO COMERCIO DE EQUIPAMENTOS E", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 213, nome: "SUPERMAX BRASIL IMPORTADORA S/A", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 214, nome: "SUZARA DALPIVA CASTELLI", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 215, nome: "TECELAGEM MINASREY LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 216, nome: "TELE SUDOESTE LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 217, nome: "TOLESUL DISTRIBUIDORA DE MEDICAMENNTO", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 218, nome: "TORTUGA TRANSP RODOV DE CARGAS EIRELI", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 219, nome: "TRANS APUCARANA TRANSPORTES RODOVIAF", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 220, nome: "TW TRANSPORTES E LOGISTICA LTDA", tipo: "Transportadora", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 221, nome: "UGHC BRASIL IMPORTADORA LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 222, nome: "UNINTER EDUCACIONAL S/A", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 223, nome: "UNITEC IND. E COM. DE APARELHOS HOSPIT/", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 224, nome: "VIA VAREJO S/A", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 225, nome: "VIEIRA & PEDOTT COMERCIO DE FERRAGENS", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 226, nome: "VISIUM BIOSSEGURANCA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 227, nome: "VITTAE REABILITACAO E PREVENCAO A SAUD", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 228, nome: "VRM DISTRIBUIDORA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 229, nome: "WAMA PRODUTOS PARA LABORATORIO LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 230, nome: "WELMY-INDUSTRIA E COMERCIO LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 231, nome: "WINNER MED LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 232, nome: "WIRECARD BRAZIL INSTITUICAO DE PAGAME", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 233, nome: "YAPAY PAGAMENTOS ONLINE LTDA.", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 234, nome: "ZASSI CAMISARIA LTDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null },
        { id: 235, nome: "ΖΕAIDE DA ROCHA FRAGATA MIRANDA", tipo: "Fornecedor", documento: null, alvara: null, dataAlvara: null, responsavelTecnico: null, registro: null, tipoRegistro: null }
    ],
    registros: [
        { id: 1, data: '2025-07-01', produto: 'DIPIRONA SODICA 500MG/ML 20ML (Código: 4573)', lote: 'LOTE001', validade: '2027-01-01', fornecedor: 'Fornecedor Exemplo', responsavel: 'otavio', status: 'Conforme', observacoes: 'Tudo OK.'}
    ],
    pops: [
        { id: 1, titulo: 'POP-001: Higienização das Mãos', setor: 'Qualidade', versao: 1, objetivo: 'Garantir a correta assepsia.', conteudo: 'Procedimento detalhado aqui.', historico: [{ versao: 1, data: new Date().toLocaleDateString('pt-BR'), descricao: 'Versão inicial criada.', responsavel: 'dani' }] }
    ],
    trelloCards: [], // Adicionado para inicializar, se não houver dados no localStorage
    proximoIdFornecedor: 236, proximoIdRegistro: 2, proximoIdPop: 2,
};